src/main/java/pt/ist/socialsoftware/edition/domain/AdHocCategory.java
package pt.ist.socialsoftware.edition.domain;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class AdHocCategory extends AdHocCategory_Base {

	@Override
	public AdHocCategory init(Taxonomy taxonomy) {
		super.init(taxonomy);
		setType(CategoryType.ADHOC);

		return this;
	}

	@Override
	public AdHocCategory init(Taxonomy taxonomy, String name) {
		super.init(taxonomy, name);
		setType(CategoryType.ADHOC);

		return this;
	}

	@Override
	public List<Tag> getSortedTags() {
		List<Tag> results = new ArrayList<Tag>(getTagSet());

		Collections.sort(results);

		return results;
	}

	@Override
	public List<Tag> getSortedActiveTags() {
		List<Tag> tags = new ArrayList<Tag>(getActiveTags());

		Collections.sort(tags);

		return tags;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/AddText.java
package pt.ist.socialsoftware.edition.domain;

import pt.ist.socialsoftware.edition.visitors.TextTreeVisitor;

public class AddText extends AddText_Base {

	public enum Place {
		ABOVE("above"), BELOW("below"), SUPERIMPOSED("superimposed"), MARGIN(
				"margin"), TOP("top"), BOTTOM("bottom"), INLINE("inline"), INSPACE(
				"inspace"), OVERLEAF("overleaf"), OPPOSITE("opposite"), END(
				"end"), UNSPECIFIED("unspecified");

		private String desc;

		Place(String desc) {
			this.desc = desc;
		}

		public String getDesc() {
			return desc;
		}
	};

	public AddText(TextPortion parent, Place place) {
		parent.addChildText(this);
		setPlace(place);
	}

	@Override
	public void accept(TextTreeVisitor visitor) {
		visitor.visit(this);
	}

	@Override
	public Boolean isFormat(Boolean displayDel, Boolean highlightSubst,
			FragInter fragInter) {
		if (getInterps().contains(fragInter)) {
			return true;
		} else {
			return false;
		}
	}

	@Override
	public String getNote() {
		String result = "Adicionado - " + getPlace().toString();

		return result;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/AltText.java
package pt.ist.socialsoftware.edition.domain;

import java.util.List;

import pt.ist.socialsoftware.edition.visitors.TextTreeVisitor;

public class AltText extends AltText_Base {

	public enum AltMode {
		EXCL("excl"), INCL("incl"), NONSPECIFIED("nonspecified");

		private final String desc;

		AltMode(String desc) {
			this.desc = desc;
		}

		public String getDesc() {
			return desc;
		}
	};

	public AltText(TextPortion parent, SegText segTextOne, SegText segTextTwo,
			AltMode mode, double weightOne, double weightTwo) {
		parent.addChildText(this);
	}

	public AltText(TextPortion parent, List<SegText> segTextList, AltMode mode,
			String[] weightList) {
		parent.addChildText(this);
		setMode(mode);

		int i = 0;
		for (SegText segText : segTextList) {
			double weight = Double.parseDouble(weightList[i]);
			addAltTextWeight(new AltTextWeight(segText, weight));
		}
	}

	@Override
	public void accept(TextTreeVisitor visitor) {
		visitor.visit(this);
	}

	@Override
	public void remove() {
		for (AltTextWeight weight : getAltTextWeightSet()) {
			weight.remove();
		}
		super.remove();
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/AltTextWeight.java
package pt.ist.socialsoftware.edition.domain;

public class AltTextWeight extends AltTextWeight_Base {

	public AltTextWeight() {
		super();
	}

	public AltTextWeight(SegText segText, double weight) {
		setSegText(segText);
		setWeight(weight);
	}

	public void remove() {
		setSegText(null);
		setAltText(null);

		deleteDomainObject();
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/AnnexNote.java
package pt.ist.socialsoftware.edition.domain;

public class AnnexNote extends AnnexNote_Base implements Comparable<AnnexNote> {

	public AnnexNote(FragInter inter, NoteText noteText) {
		setFragInter(inter);
		setNoteText(noteText);

		int number = getFragInter().getNumAnnexNotes() + 1;
		setNumber(number);
		getFragInter().setNumAnnexNotes(number);
	}

	public AnnexNote(FragInter inter) {
		setFragInter(inter);

		int number = getFragInter().getNumAnnexNotes() + 1;
		setNumber(number);
		getFragInter().setNumAnnexNotes(number);
	}

	public void remove() {
		setFragInter(null);
		setNoteText(null);

		deleteDomainObject();
	}

	@Override
	public int compareTo(AnnexNote o) {
		return getNumber() > o.getNumber() ? +1
				: getNumber() < o.getNumber() ? -1 : 0;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/Annotation.java
package pt.ist.socialsoftware.edition.domain;

import java.util.List;

import pt.ist.fenixframework.Atomic;
import pt.ist.fenixframework.Atomic.TxMode;

public class Annotation extends Annotation_Base {

	public Annotation(FragInter inter, SimpleText startText,
			SimpleText endText, String quote, String text, LdoDUser user) {
		setFragInter(inter);
		setStartText(startText);
		setEndText(endText);
		setQuote(quote);
		setText(text);
		setUser(user);
	}

	@Atomic(mode = TxMode.WRITE)
	public void remove() {
		setFragInter(null);
		setUser(null);
		setStartText(null);
		setEndText(null);

		for (Range range : getRangeSet()) {
			range.remove();
		}

		for (UserTagInTextPortion tag : getUserTagInTextPortionSet()) {
			tag.remove();
		}

		deleteDomainObject();
	}

	private Taxonomy getTaxonomy() {
		for (UserTagInTextPortion tagInTextPortion : getUserTagInTextPortionSet()) {
			return tagInTextPortion.getCategory().getTaxonomy();
		}
		return null;
	}

	public void updateTags(List<String> tags) {
		for (String tag : tags) {
			if (!existsActiveTag(tag)) {
				getFragInter().createUserTagInTextPortion(getTaxonomy(), this,
						tag);
			}
		}

		for (UserTagInTextPortion tag : getUserTagInTextPortionSet()) {
			if (!tags
					.contains(tag.getActiveTag().getActiveCategory().getName())) {
				tag.removeThisAnnotation(this);
			}
		}
	}

	private boolean existsActiveTag(String name) {
		for (UserTagInTextPortion tag : getUserTagInTextPortionSet()) {
			if (tag.getActiveTag().getActiveCategory().getName().equals(name)) {
				return true;
			}
		}
		return false;
	}

	@Atomic(mode = TxMode.WRITE)
	public void update(String text, List<String> tags) {
		setText(text);
		updateTags(tags);
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/AppText.java
package pt.ist.socialsoftware.edition.domain;

import java.util.List;

import pt.ist.socialsoftware.edition.visitors.TextTreeVisitor;

public class AppText extends AppText_Base {

	public AppText(TextPortion parent, VariationType type) {
		if (parent != null) {
			parent.addChildText(this);
		}

		setType(type);
	}

	public AppText(VariationType type) {
		setParentText(null);

		setType(type);
	}

	@Override
	public void accept(TextTreeVisitor visitor) {
		visitor.visit(this);
	}

	@Override
	protected TextPortion getNextChildText(FragInter inter) {
		if (this.getInterps().contains(inter)) {
			for (TextPortion childText : getChildTextSet()) {
				if (childText.getInterps().contains(inter)) {
					return childText;
				}
			}
		}
		return null;
	}

	@Override
	public void putAppTextWithVariations(List<AppText> apps,
			List<FragInter> inters) {

		if (hasVariations(inters)) {
			apps.add(this);
		}
	}

	@Override
	public boolean hasVariations(List<FragInter> inters) {
		for (TextPortion text : getChildTextSet()) {
			if (text.hasVariations(inters)) {
				return true;
			}
		}
		return false;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/Category.java
package pt.ist.socialsoftware.edition.domain;

import java.util.HashSet;
import java.util.List;
import java.util.Set;

import pt.ist.fenixframework.Atomic;
import pt.ist.fenixframework.Atomic.TxMode;
import pt.ist.socialsoftware.edition.shared.exception.LdoDDuplicateNameException;

public abstract class Category extends Category_Base implements
		Comparable<Category> {

	public enum CategoryType {
		GENERATED("generated"), ADHOC("adhoc"), MERGED("merged"), EXTRACTED(
				"extracted");

		private final String desc;

		CategoryType(String desc) {
			this.desc = desc;
		}

		public String getDesc() {
			return desc;
		}
	};

	public Category init(Taxonomy taxonomy) {
		setTaxonomy(taxonomy);
		setDeprecated(false);

		return this;
	}

	public Category init(Taxonomy taxonomy, String name) {
		setTaxonomy(taxonomy);
		setName(name);
		setDeprecated(false);

		return this;
	}

	@Atomic(mode = TxMode.WRITE)
	public void remove() {
		setTaxonomy(null);

		if (getMergeCategory() != null)
			getMergeCategory().remove();

		for (SplitCategory category : getSplitCategorySet()) {
			category.remove();
		}

		for (Tag tag : getTagSet()) {
			tag.remove();
		}

		deleteDomainObject();
	}

	@Atomic(mode = TxMode.WRITE)
	@Override
	public void setName(String name) {
		for (Category category : getTaxonomy().getActiveCategorySet()) {
			if ((category != this) && (category.getName().equals(name))) {
				throw new LdoDDuplicateNameException();
			}
		}
		super.setName(name);
	}

	@Override
	public int compareTo(Category other) {
		return getName().compareTo(other.getName());
	}

	protected Set<Tag> getActiveTags() {
		Set<Tag> tags = new HashSet<Tag>();
		for (Tag tag : getTagSet()) {
			if (!tag.getDeprecated()) {
				tags.add(tag);
			}
		}
		return tags;
	}

	abstract public List<Tag> getSortedTags();

	abstract public List<Tag> getSortedActiveTags();

	public Tag getTag(FragInter fragInter) {
		for (Tag tag : getTagSet()) {
			if (tag.getFragInter() == fragInter)
				return tag;
		}
		return null;
	}

	public Category getActiveCategory() {
		if (!getDeprecated()) {
			return this;
		} else if (getMergeCategory() != null) {
			return getMergeCategory().getActiveCategory();
		} else {
			return null;
		}
	}
}

src/main/java/pt/ist/socialsoftware/edition/domain/DelText.java
package pt.ist.socialsoftware.edition.domain;

import pt.ist.socialsoftware.edition.visitors.TextTreeVisitor;

public class DelText extends DelText_Base {

	public enum HowDel {
		OVERSTRIKE("overstrike"), OVERTYPED("overtyped"), OVERWRITTEN(
				"overwritten"), UNSPECIFIED("unspecified");

		private String desc;

		HowDel(String desc) {
			this.desc = desc;
		}

		public String getDesc() {
			return desc;
		}
	};

	public DelText(TextPortion parent, HowDel how) {
		parent.addChildText(this);
		setHow(how);
	}

	@Override
	public void accept(TextTreeVisitor visitor) {
		visitor.visit(this);
	}

	@Override
	public Boolean isFormat(Boolean displayDel, Boolean highlightSubst,
			FragInter fragInter) {
		if (getInterps().contains(fragInter) && displayDel) {
			return true;
		} else {
			return false;
		}
	}

	@Override
	public String getNote() {
		String result = "Retirado - " + getHow().toString();

		return result;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/Edition.java
package pt.ist.socialsoftware.edition.domain;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;

import pt.ist.socialsoftware.edition.shared.exception.LdoDDuplicateAcronymException;

public abstract class Edition extends Edition_Base {

	public enum EditionType {
		AUTHORIAL("authorial"), EDITORIAL("editorial"), VIRTUAL("virtual");

		private final String desc;

		EditionType(String desc) {
			this.desc = desc;
		}

		public String getDesc() {
			return desc;
		}
	};

	public void remove() {
		for (Taxonomy taxonomy : getTaxonomiesSet()) {
			taxonomy.remove();
		}

		deleteDomainObject();
	}

	@Override
	public void setAcronym(String acronym) {
		if ((getAcronym() != null && !getAcronym().equals(acronym))
				|| getAcronym() == null) {
			for (ExpertEdition edition : LdoD.getInstance()
					.getExpertEditionsSet()) {
				if (acronym.equals(edition.getAcronym())) {
					throw new LdoDDuplicateAcronymException();
				}
			}

			for (VirtualEdition edition : LdoD.getInstance()
					.getVirtualEditionsSet()) {
				if (acronym.equals(edition.getAcronym())) {
					throw new LdoDDuplicateAcronymException();
				}
			}
		}

		super.setAcronym(acronym);
	}

	public abstract EditionType getSourceType();

	public abstract Set<FragInter> getIntersSet();

	public abstract String getReference();

	public List<FragInter> getSortedInterps() {
		List<FragInter> interps = new ArrayList<FragInter>(getIntersSet());

		Collections.sort(interps);

		return interps;
	}

	public FragInter getNextNumberInter(FragInter inter, int number) {
		List<FragInter> interps = new ArrayList<FragInter>(inter.getEdition()
				.getIntersSet());

		Collections.sort(interps);

		return findNextElementByNumber(inter, number, interps);
	}

	public FragInter getPrevNumberInter(FragInter inter, int number) {
		List<FragInter> interps = new ArrayList<FragInter>(inter.getEdition()
				.getIntersSet());

		Collections.sort(interps, Collections.reverseOrder());

		return findNextElementByNumber(inter, number, interps);
	}

	private FragInter findNextElementByNumber(FragInter inter, int number,
			List<FragInter> interps) {
		Boolean stopNext = false;
		for (FragInter tmpInter : interps) {
			if (stopNext) {
				return tmpInter;
			}
			if ((tmpInter.getNumber() == number) && tmpInter == inter) {
				stopNext = true;
			}
		}
		return interps.get(0);
	}

	public Taxonomy getTaxonomy(String name) {
		for (Taxonomy taxonomy : getTaxonomiesSet()) {
			if (name.equals(taxonomy.getName())) {
				return taxonomy;
			}
		}
		return null;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/ExpertEditionInter.java
package pt.ist.socialsoftware.edition.domain;

import java.util.ArrayList;
import java.util.List;

import pt.ist.socialsoftware.edition.domain.Edition.EditionType;
import pt.ist.socialsoftware.edition.utils.search.options.SearchOption;

public class ExpertEditionInter extends ExpertEditionInter_Base {

	public ExpertEditionInter() {
		setNotes("");
		setVolume("");
	}

	@Override
	public void remove() {
		setExpertEdition(null);

		super.remove();
	}

	@Override
	public String getShortName() {
		return getExpertEdition().getEditorShortName();
	}

	@Override
	public String getTitle() {
		String fragTitle = super.getTitle();
		if (fragTitle == null || fragTitle.trim().equals("")) {
			return getFragment().getTitle();
		} else {
			return fragTitle;
		}
	}

	@Override
	public EditionType getSourceType() {
		return EditionType.EDITORIAL;
	}

	public int compareExpertEditionInter(ExpertEditionInter other) {
		String myEditor = getExpertEdition().getEditor();
		String otherEditor = other.getExpertEdition().getEditor();

		if (myEditor.equals(otherEditor)) {
			return compareNumber(other);
		} else if (myEditor.equals(ExpertEdition.COELHO)) {
			return -1;
		} else if (otherEditor.equals(ExpertEdition.COELHO)) {
			return 1;
		} else if (myEditor.equals(ExpertEdition.CUNHA)) {
			return -1;
		} else if (otherEditor.equals(ExpertEdition.CUNHA)) {
			return 1;
		} else if (myEditor.equals(ExpertEdition.ZENITH)) {
			return -1;
		} else if (otherEditor.equals(ExpertEdition.ZENITH)) {
			return 1;
		} else {
			assert false : "To extend when new expert editions are include";
		return 0;
		}
	}

	public int compareNumber(ExpertEditionInter other) {
		if (getNumber() == other.getNumber()) {
			return comparePage(getStartPage(), other.getStartPage());
		} else if (getNumber() < other.getNumber()) {
			return -1;
		} else
			return 1;
	}

	private int comparePage(int page1, int page2) {
		if (page1 < page2)
			return -1;
		else if (page1 == page2)
			return 0;
		else
			return 1;

	}

	@Override
	public String getMetaTextual() {
		String result = "";

		result = result + "Título: " + getTitle() + "<br>";

		result = result + "Heterónimo: " + getHeteronym().getName() + "<br>";

		String number = getNumber() == 0 ? "" : Integer.toString(getNumber());
		result = result + "Número: " + number + "<br>";

		result = result + "Volume: " + getVolume() + "<br>";

		result = result + "Página: " + getStartPage() + "<br>";

		if (getDate() != null) {
			String precision = getPrecision() != null ? " Precisão: "
					+ getPrecision().getDesc() : "";

					result = result + "Data: " + getDate().toString("dd-MM-yyyy")
							+ precision + "<br>";
		}

		result = result + "Notas: " + getNotes() + "<br>";

		return result + super.getMetaTextual();
	}

	@Override
	public boolean belongs2Edition(Edition edition) {
		return this.getExpertEdition() == edition;
	}

	@Override
	public FragInter getLastUsed() {
		return this;
	}

	@Override
	public Edition getEdition() {
		return getExpertEdition();
	}

	@Override
	public List<FragInter> getListUsed() {
		List<FragInter> listUses = new ArrayList<FragInter>();
		return listUses;
	}

	@Override
	public String getReference() {
		return Integer.toString(getNumber());
	}

	@Override
	public boolean accept(SearchOption option){
		return option.visit(this);
	}
}

src/main/java/pt/ist/socialsoftware/edition/domain/Facsimile.java
package pt.ist.socialsoftware.edition.domain;

import java.util.ArrayList;
import java.util.List;

public class Facsimile extends Facsimile_Base {

	public Facsimile(Source source, String xmlID) {
		setSource(source);
		setXmlId(xmlID);
	}

	public void addSurface(Surface surface) {
		Surface firstSurface = getFirstSurface();
		if (firstSurface == null) {
			setFirstSurface(surface);
			surface.setPrev(null);
			surface.setNext(null);
		} else {
			firstSurface.addSurface(surface);
		}
	}

	public List<Surface> getSurfaces() {
		List<Surface> surfaces = new ArrayList<Surface>();
		Surface surface = getFirstSurface();

		while (surface != null) {
			surfaces.add(surface);
			surface = surface.getNext();
		}

		return surfaces;
	}

	public void remove() {
		setSource(null);

		if (getFirstSurface() != null) {
			getFirstSurface().remove();
		}

		deleteDomainObject();
	}

}

src/main/webapp/WEB-INF/jsp/edition/categoryTableOfContents.jsp
<%@ include file="/WEB-INF/jsp/common/tags-head.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<%@ include file="/WEB-INF/jsp/common/meta-head.jsp"%>
</head>
<body>
    <%@ include file="/WEB-INF/jsp/common/fixed-top-ldod-header.jsp"%>

    <div class="container">
        <h3 class="text-center">
            <spring:message code="virtualedition" />
            : <a
                href="${contextPath}/edition/internalid/${category.getTaxonomy().getEdition().getExternalId()}">
                ${category.getTaxonomy().getEdition().title}</a>
            <spring:message code="general.taxonomy" />
            : <a
                href="${contextPath}/edition/taxonomy/${category.getTaxonomy().getExternalId()}">${category.getTaxonomy().getName()}</a>
            <spring:message code="general.category" />
            : ${category.getName()} (${category.getTagSet().size()})
        </h3>

        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th><spring:message
                            code="tableofcontents.title" /></th>
                    <c:if test="${taxonomy.getAdHoc() }">
                        <th><spring:message code="general.weight" /></th>
                    </c:if>
                    <th><spring:message
                            code="tableofcontents.usesEditions" /></th>
                    <th><spring:message
                            code="tableofcontents.number" /></th>
                </tr>
            <tbody>
                <c:forEach var="categoryInFragInter"
                    items='${category.getSortedActiveTags()}'>
                    <tr>
                        <td><a
                            href="${contextPath}/fragments/fragment/inter/${categoryInFragInter.getFragInter().getExternalId()}">${categoryInFragInter.getFragInter().getTitle()}</a></td>
                        <c:if test="${taxonomy.getAdHoc() }">
                            <td>${categoryInFragInter.getWeight()}</td>
                        </c:if>
                        <td><c:forEach var="used"
                                items="${categoryInFragInter.getFragInter().getListUsed()}">-><a
                                    href="${contextPath}/fragments/fragment/inter/${used.externalId}">${used.shortName}</a>
                            </c:forEach></td>
                        <td>${categoryInFragInter.getFragInter().getNumber()}</td>
                    </tr>
                </c:forEach>
            </tbody>
        </table>
    </div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/edition/expertTableOfContents.jsp
<%@ include file="/WEB-INF/jsp/common/tags-head.jsp"%>
<h3 class="text-center">
    <spring:message code="tableofcontents.editionof" />
    ${edition.editor} (${edition.getSortedInterps().size()})
</h3>
<c:if test="${heteronym != null}">
    <h4 class="text-left">
        <spring:message code="tableofcontents.fragmentsof" />
        ${heteronym.name}
    </h4>
</c:if>

<table class="table table-hover table-condensed">
    <thead>
        <tr>
            <th><spring:message code="tableofcontents.number" /></th>
            <th><spring:message code="tableofcontents.title" /></th>
            <th><spring:message code="tableofcontents.volume" /></th>
            <th><spring:message code="tableofcontents.page" /></th>
            <th><spring:message code="general.date" /></th>
            <th><spring:message code="general.heteronym" /></th>
        </tr>
    <tbody>
        <c:forEach var="interp" items='${edition.sortedInterps}'>
            <c:if
                test="${(heteronym == null) || (interp.heteronym == heteronym)}">
                <tr>
                    <td><c:if test="${interp.number!=0}">${interp.number}</c:if></td>
                    <td><a
                        href="${contextPath}/fragments/fragment/inter/${interp.externalId}">${interp.title}</a></td>
                    <td>${interp.volume}</td>
                    <td>${interp.startPage}</td>
                    <td>${interp.getDate().toString("dd-MM-yyyy")}</td>
                    <td>${interp.getHeteronym().getName()}</td>
                </tr>
            </c:if>
        </c:forEach>
    </tbody>
</table>

src/main/webapp/WEB-INF/jsp/edition/tableOfContents.jsp
<%@ include file="/WEB-INF/jsp/common/tags-head.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<%@ include file="/WEB-INF/jsp/common/meta-head.jsp"%>
</head>
<body>
    <%@ include file="/WEB-INF/jsp/common/fixed-top-ldod-header.jsp"%>

    <div class="container">
        <c:choose> <c:when
            test="${edition.sourceType == 'EDITORIAL'}"><%@ include
                file="/WEB-INF/jsp/edition/expertTableOfContents.jsp"%></c:when>
        <c:when test="${edition.getSourceType() == 'VIRTUAL'}"><%@ include
                file="/WEB-INF/jsp/edition/virtualTableOfContents.jsp"%></c:when>
        </c:choose>
    </div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/edition/taxonomyTableOfContents.jsp
<%@ include file="/WEB-INF/jsp/common/tags-head.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<%@ include file="/WEB-INF/jsp/common/meta-head.jsp"%>
</head>
<body>
    <%@ include file="/WEB-INF/jsp/common/fixed-top-ldod-header.jsp"%>

    <div class="container">
        <h3 class="text-center">
            <spring:message code="virtualedition" /> <a href="${contextPath}/edition/internalid/${taxonomy.getEdition().getExternalId()}"> ${taxonomy.getEdition().title}</a>
            <spring:message code="general.taxonomy" />: ${taxonomy.getName()} (${taxonomy.getSortedFragInter().size()})
        </h3>

        <table class="table table-hover table-condensed">
            <thead>
                <tr>
                    <th><spring:message
                            code="tableofcontents.title" /></th>
                    <th><spring:message code="general.category" /></th>
                    <th><spring:message
                            code="tableofcontents.number" /></th>
                    <th><spring:message
                            code="tableofcontents.usesEditions" /></th>
                </tr>
            <tbody>
                <c:forEach var="inter"
                    items='${taxonomy.getSortedFragInter()}'>
                    <tr>
                        <td><a
                            href="${contextPath}/fragments/fragment/inter/${inter.getExternalId()}">${inter.getTitle()}</a></td>
                        <td>
                            <c:forEach var="tag" items='${taxonomy.getSortedActiveTags(inter)}'> 
                                <a href="${contextPath}/edition/category/${tag.getCategory().getExternalId()}">
                                    ${tag.getCategory().getName()}
                                </a> <c:if test="${taxonomy.getAdHoc() }">(${tag.getWeight()})</c:if>
                            </c:forEach>
                        </td>
                        <td>${inter.getNumber()}</td>
                        <td><c:forEach var="used"
                                items="${inter.getListUsed()}">-><a
                                    href="${contextPath}/fragments/fragment/inter/${used.externalId}">${used.shortName}</a>
                            </c:forEach></td>
                    </tr>
                </c:forEach>

            </tbody>
        </table>
    </div>
</body>
</html>

src/main/webapp/WEB-INF/jsp/edition/virtualTableOfContents.jsp
<%@ include file="/WEB-INF/jsp/common/tags-head.jsp"%>
<h3 class="text-center">
    <spring:message code="virtualedition" />
    ${edition.title} (${edition.getSortedInterps().size()})
</h3>
<c:if test="${heteronym != null}">
    <h4 class="text-left">
        <spring:message code="tableofcontents.fragmentsof" />
        ${heteronym.name}
    </h4>
</c:if>

<table class="table table-condensed table-hover">
    <thead>
        <tr>
            <th><spring:message code="tableofcontents.number" /></th>
            <th><spring:message code="tableofcontents.title" /></th>
            <th><spring:message code="general.taxonomy" /></th>
            <th><spring:message code="tableofcontents.usesEditions" /></th>
        </tr>
    <tbody>
        <c:forEach var="inter" items='${edition.sortedInterps}'>
            <c:if
                test="${(heteronym == null) || (inter.heteronym == heteronym)}">
                <tr>
                    <td><c:if test="${inter.number!=0}">${inter.number}</c:if></td>
                    <td><a
                        href="${contextPath}/fragments/fragment/inter/${inter.externalId}">${inter.title}</a></td>
                    <td>
                        <c:forEach var="taxonomy" items="${edition.getTaxonomies()}">
                            <a href="${contextPath}/edition/taxonomy/${taxonomy.getExternalId()}">${taxonomy.getName()}</a>
                        </c:forEach>
                    </td>
                    <td><c:forEach var="used"
                            items="${inter.getListUsed()}">-><a
                        href="${contextPath}/fragments/fragment/inter/${used.externalId}">${used.shortName}</a>
                    </c:forEach></td>
                </tr>
            </c:if>
        </c:forEach>
    </tbody>
</table>