src/main/java/pt/ist/socialsoftware/edition/domain/AdHocCategory.java
package pt.ist.socialsoftware.edition.domain;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class AdHocCategory extends AdHocCategory_Base {

	@Override
	public AdHocCategory init(Taxonomy taxonomy) {
		super.init(taxonomy);
		setType(CategoryType.ADHOC);

		return this;
	}

	@Override
	public AdHocCategory init(Taxonomy taxonomy, String name) {
		super.init(taxonomy, name);
		setType(CategoryType.ADHOC);

		return this;
	}

	@Override
	public List<Tag> getSortedTags() {
		List<Tag> results = new ArrayList<Tag>(getTagSet());

		Collections.sort(results);

		return results;
	}

	@Override
	public List<Tag> getSortedActiveTags() {
		List<Tag> tags = new ArrayList<Tag>(getActiveTags());

		Collections.sort(tags);

		return tags;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/AddText.java
package pt.ist.socialsoftware.edition.domain;

import pt.ist.socialsoftware.edition.visitors.TextTreeVisitor;

public class AddText extends AddText_Base {

	public enum Place {
		ABOVE("above"), BELOW("below"), SUPERIMPOSED("superimposed"), MARGIN(
				"margin"), TOP("top"), BOTTOM("bottom"), INLINE("inline"), INSPACE(
				"inspace"), OVERLEAF("overleaf"), OPPOSITE("opposite"), END(
				"end"), UNSPECIFIED("unspecified");

		private String desc;

		Place(String desc) {
			this.desc = desc;
		}

		public String getDesc() {
			return desc;
		}
	};

	public AddText(TextPortion parent, Place place) {
		parent.addChildText(this);
		setPlace(place);
	}

	@Override
	public void accept(TextTreeVisitor visitor) {
		visitor.visit(this);
	}

	@Override
	public Boolean isFormat(Boolean displayDel, Boolean highlightSubst,
			FragInter fragInter) {
		if (getInterps().contains(fragInter)) {
			return true;
		} else {
			return false;
		}
	}

	@Override
	public String getNote() {
		String result = "Adicionado - " + getPlace().toString();

		return result;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/AltText.java
package pt.ist.socialsoftware.edition.domain;

import java.util.List;

import pt.ist.socialsoftware.edition.visitors.TextTreeVisitor;

public class AltText extends AltText_Base {

	public enum AltMode {
		EXCL("excl"), INCL("incl"), NONSPECIFIED("nonspecified");

		private final String desc;

		AltMode(String desc) {
			this.desc = desc;
		}

		public String getDesc() {
			return desc;
		}
	};

	public AltText(TextPortion parent, SegText segTextOne, SegText segTextTwo,
			AltMode mode, double weightOne, double weightTwo) {
		parent.addChildText(this);
	}

	public AltText(TextPortion parent, List<SegText> segTextList, AltMode mode,
			String[] weightList) {
		parent.addChildText(this);
		setMode(mode);

		int i = 0;
		for (SegText segText : segTextList) {
			double weight = Double.parseDouble(weightList[i]);
			addAltTextWeight(new AltTextWeight(segText, weight));
		}
	}

	@Override
	public void accept(TextTreeVisitor visitor) {
		visitor.visit(this);
	}

	@Override
	public void remove() {
		for (AltTextWeight weight : getAltTextWeightSet()) {
			weight.remove();
		}
		super.remove();
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/AltTextWeight.java
package pt.ist.socialsoftware.edition.domain;

public class AltTextWeight extends AltTextWeight_Base {

	public AltTextWeight() {
		super();
	}

	public AltTextWeight(SegText segText, double weight) {
		setSegText(segText);
		setWeight(weight);
	}

	public void remove() {
		setSegText(null);
		setAltText(null);

		deleteDomainObject();
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/AnnexNote.java
package pt.ist.socialsoftware.edition.domain;

public class AnnexNote extends AnnexNote_Base implements Comparable<AnnexNote> {

	public AnnexNote(FragInter inter, NoteText noteText) {
		setFragInter(inter);
		setNoteText(noteText);

		int number = getFragInter().getNumAnnexNotes() + 1;
		setNumber(number);
		getFragInter().setNumAnnexNotes(number);
	}

	public AnnexNote(FragInter inter) {
		setFragInter(inter);

		int number = getFragInter().getNumAnnexNotes() + 1;
		setNumber(number);
		getFragInter().setNumAnnexNotes(number);
	}

	public void remove() {
		setFragInter(null);
		setNoteText(null);

		deleteDomainObject();
	}

	@Override
	public int compareTo(AnnexNote o) {
		return getNumber() > o.getNumber() ? +1
				: getNumber() < o.getNumber() ? -1 : 0;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/Annotation.java
package pt.ist.socialsoftware.edition.domain;

import java.util.List;

import pt.ist.fenixframework.Atomic;
import pt.ist.fenixframework.Atomic.TxMode;

public class Annotation extends Annotation_Base {

	public Annotation(FragInter inter, SimpleText startText,
			SimpleText endText, String quote, String text, LdoDUser user) {
		setFragInter(inter);
		setStartText(startText);
		setEndText(endText);
		setQuote(quote);
		setText(text);
		setUser(user);
	}

	@Atomic(mode = TxMode.WRITE)
	public void remove() {
		setFragInter(null);
		setUser(null);
		setStartText(null);
		setEndText(null);

		for (Range range : getRangeSet()) {
			range.remove();
		}

		for (UserTagInTextPortion tag : getUserTagInTextPortionSet()) {
			tag.remove();
		}

		deleteDomainObject();
	}

	private Taxonomy getTaxonomy() {
		for (UserTagInTextPortion tagInTextPortion : getUserTagInTextPortionSet()) {
			return tagInTextPortion.getCategory().getTaxonomy();
		}
		return null;
	}

	public void updateTags(List<String> tags) {
		for (String tag : tags) {
			if (!existsActiveTag(tag)) {
				getFragInter().createUserTagInTextPortion(getTaxonomy(), this,
						tag);
			}
		}

		for (UserTagInTextPortion tag : getUserTagInTextPortionSet()) {
			if (!tags
					.contains(tag.getActiveTag().getActiveCategory().getName())) {
				tag.removeThisAnnotation(this);
			}
		}
	}

	private boolean existsActiveTag(String name) {
		for (UserTagInTextPortion tag : getUserTagInTextPortionSet()) {
			if (tag.getActiveTag().getActiveCategory().getName().equals(name)) {
				return true;
			}
		}
		return false;
	}

	@Atomic(mode = TxMode.WRITE)
	public void update(String text, List<String> tags) {
		setText(text);
		updateTags(tags);
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/AppText.java
package pt.ist.socialsoftware.edition.domain;

import java.util.List;

import pt.ist.socialsoftware.edition.visitors.TextTreeVisitor;

public class AppText extends AppText_Base {

	public AppText(TextPortion parent, VariationType type) {
		if (parent != null) {
			parent.addChildText(this);
		}

		setType(type);
	}

	public AppText(VariationType type) {
		setParentText(null);

		setType(type);
	}

	@Override
	public void accept(TextTreeVisitor visitor) {
		visitor.visit(this);
	}

	@Override
	protected TextPortion getNextChildText(FragInter inter) {
		if (this.getInterps().contains(inter)) {
			for (TextPortion childText : getChildTextSet()) {
				if (childText.getInterps().contains(inter)) {
					return childText;
				}
			}
		}
		return null;
	}

	@Override
	public void putAppTextWithVariations(List<AppText> apps,
			List<FragInter> inters) {

		if (hasVariations(inters)) {
			apps.add(this);
		}
	}

	@Override
	public boolean hasVariations(List<FragInter> inters) {
		for (TextPortion text : getChildTextSet()) {
			if (text.hasVariations(inters)) {
				return true;
			}
		}
		return false;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/DelText.java
package pt.ist.socialsoftware.edition.domain;

import pt.ist.socialsoftware.edition.visitors.TextTreeVisitor;

public class DelText extends DelText_Base {

	public enum HowDel {
		OVERSTRIKE("overstrike"), OVERTYPED("overtyped"), OVERWRITTEN(
				"overwritten"), UNSPECIFIED("unspecified");

		private String desc;

		HowDel(String desc) {
			this.desc = desc;
		}

		public String getDesc() {
			return desc;
		}
	};

	public DelText(TextPortion parent, HowDel how) {
		parent.addChildText(this);
		setHow(how);
	}

	@Override
	public void accept(TextTreeVisitor visitor) {
		visitor.visit(this);
	}

	@Override
	public Boolean isFormat(Boolean displayDel, Boolean highlightSubst,
			FragInter fragInter) {
		if (getInterps().contains(fragInter) && displayDel) {
			return true;
		} else {
			return false;
		}
	}

	@Override
	public String getNote() {
		String result = "Retirado - " + getHow().toString();

		return result;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/Edition.java
package pt.ist.socialsoftware.edition.domain;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.Set;

import pt.ist.socialsoftware.edition.shared.exception.LdoDDuplicateAcronymException;

public abstract class Edition extends Edition_Base {

	public enum EditionType {
		AUTHORIAL("authorial"), EDITORIAL("editorial"), VIRTUAL("virtual");

		private final String desc;

		EditionType(String desc) {
			this.desc = desc;
		}

		public String getDesc() {
			return desc;
		}
	};

	public void remove() {
		for (Taxonomy taxonomy : getTaxonomiesSet()) {
			taxonomy.remove();
		}

		deleteDomainObject();
	}

	@Override
	public void setAcronym(String acronym) {
		if ((getAcronym() != null && !getAcronym().equals(acronym))
				|| getAcronym() == null) {
			for (ExpertEdition edition : LdoD.getInstance()
					.getExpertEditionsSet()) {
				if (acronym.equals(edition.getAcronym())) {
					throw new LdoDDuplicateAcronymException();
				}
			}

			for (VirtualEdition edition : LdoD.getInstance()
					.getVirtualEditionsSet()) {
				if (acronym.equals(edition.getAcronym())) {
					throw new LdoDDuplicateAcronymException();
				}
			}
		}

		super.setAcronym(acronym);
	}

	public abstract EditionType getSourceType();

	public abstract Set<FragInter> getIntersSet();

	public abstract String getReference();

	public List<FragInter> getSortedInterps() {
		List<FragInter> interps = new ArrayList<FragInter>(getIntersSet());

		Collections.sort(interps);

		return interps;
	}

	public FragInter getNextNumberInter(FragInter inter, int number) {
		List<FragInter> interps = new ArrayList<FragInter>(inter.getEdition()
				.getIntersSet());

		Collections.sort(interps);

		return findNextElementByNumber(inter, number, interps);
	}

	public FragInter getPrevNumberInter(FragInter inter, int number) {
		List<FragInter> interps = new ArrayList<FragInter>(inter.getEdition()
				.getIntersSet());

		Collections.sort(interps, Collections.reverseOrder());

		return findNextElementByNumber(inter, number, interps);
	}

	private FragInter findNextElementByNumber(FragInter inter, int number,
			List<FragInter> interps) {
		Boolean stopNext = false;
		for (FragInter tmpInter : interps) {
			if (stopNext) {
				return tmpInter;
			}
			if ((tmpInter.getNumber() == number) && tmpInter == inter) {
				stopNext = true;
			}
		}
		return interps.get(0);
	}

	public Taxonomy getTaxonomy(String name) {
		for (Taxonomy taxonomy : getTaxonomiesSet()) {
			if (name.equals(taxonomy.getName())) {
				return taxonomy;
			}
		}
		return null;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/ExpertEditionInter.java
package pt.ist.socialsoftware.edition.domain;

import java.util.ArrayList;
import java.util.List;

import pt.ist.socialsoftware.edition.domain.Edition.EditionType;
import pt.ist.socialsoftware.edition.utils.search.options.SearchOption;

public class ExpertEditionInter extends ExpertEditionInter_Base {

	public ExpertEditionInter() {
		setNotes("");
		setVolume("");
	}

	@Override
	public void remove() {
		setExpertEdition(null);

		super.remove();
	}

	@Override
	public String getShortName() {
		return getExpertEdition().getEditorShortName();
	}

	@Override
	public String getTitle() {
		String fragTitle = super.getTitle();
		if (fragTitle == null || fragTitle.trim().equals("")) {
			return getFragment().getTitle();
		} else {
			return fragTitle;
		}
	}

	@Override
	public EditionType getSourceType() {
		return EditionType.EDITORIAL;
	}

	public int compareExpertEditionInter(ExpertEditionInter other) {
		String myEditor = getExpertEdition().getEditor();
		String otherEditor = other.getExpertEdition().getEditor();

		if (myEditor.equals(otherEditor)) {
			return compareNumber(other);
		} else if (myEditor.equals(ExpertEdition.COELHO)) {
			return -1;
		} else if (otherEditor.equals(ExpertEdition.COELHO)) {
			return 1;
		} else if (myEditor.equals(ExpertEdition.CUNHA)) {
			return -1;
		} else if (otherEditor.equals(ExpertEdition.CUNHA)) {
			return 1;
		} else if (myEditor.equals(ExpertEdition.ZENITH)) {
			return -1;
		} else if (otherEditor.equals(ExpertEdition.ZENITH)) {
			return 1;
		} else {
			assert false : "To extend when new expert editions are include";
		return 0;
		}
	}

	public int compareNumber(ExpertEditionInter other) {
		if (getNumber() == other.getNumber()) {
			return comparePage(getStartPage(), other.getStartPage());
		} else if (getNumber() < other.getNumber()) {
			return -1;
		} else
			return 1;
	}

	private int comparePage(int page1, int page2) {
		if (page1 < page2)
			return -1;
		else if (page1 == page2)
			return 0;
		else
			return 1;

	}

	@Override
	public String getMetaTextual() {
		String result = "";

		result = result + "Título: " + getTitle() + "<br>";

		result = result + "Heterónimo: " + getHeteronym().getName() + "<br>";

		String number = getNumber() == 0 ? "" : Integer.toString(getNumber());
		result = result + "Número: " + number + "<br>";

		result = result + "Volume: " + getVolume() + "<br>";

		result = result + "Página: " + getStartPage() + "<br>";

		if (getDate() != null) {
			String precision = getPrecision() != null ? " Precisão: "
					+ getPrecision().getDesc() : "";

					result = result + "Data: " + getDate().toString("dd-MM-yyyy")
							+ precision + "<br>";
		}

		result = result + "Notas: " + getNotes() + "<br>";

		return result + super.getMetaTextual();
	}

	@Override
	public boolean belongs2Edition(Edition edition) {
		return this.getExpertEdition() == edition;
	}

	@Override
	public FragInter getLastUsed() {
		return this;
	}

	@Override
	public Edition getEdition() {
		return getExpertEdition();
	}

	@Override
	public List<FragInter> getListUsed() {
		List<FragInter> listUses = new ArrayList<FragInter>();
		return listUses;
	}

	@Override
	public String getReference() {
		return Integer.toString(getNumber());
	}

	@Override
	public boolean accept(SearchOption option){
		return option.visit(this);
	}
}

src/main/java/pt/ist/socialsoftware/edition/domain/FragWord.java
package pt.ist.socialsoftware.edition.domain;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class FragWord extends FragWord_Base {

	public FragWord(Taxonomy taxonomy, String word) {
		setTaxonomy(taxonomy);
		setWord(word);
	}

	public void remove() {
		setTaxonomy(null);

		for (FragWordInCategory fragWordInCategory : getFragWordInCategorySet()) {
			fragWordInCategory.remove();
		}

		deleteDomainObject();
	}

	public List<FragWordInCategory> getSortedFragWordInCategory() {
		List<FragWordInCategory> results = new ArrayList<FragWordInCategory>(
				getFragWordInCategorySet());

		Collections.sort(results);

		return results;
	}

}

src/main/java/pt/ist/socialsoftware/edition/domain/Fragment.java
package pt.ist.socialsoftware.edition.domain;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import pt.ist.fenixframework.Atomic;
import pt.ist.fenixframework.Atomic.TxMode;
import pt.ist.socialsoftware.edition.domain.Edition.EditionType;

public class Fragment extends Fragment_Base {

	public enum PrecisionType {
		HIGH("high"), MEDIUM("medium"), LOW("low"), UNKNOWN("unknown");

		private final String desc;

		PrecisionType(String desc) {
			this.desc = desc;
		}

		public String getDesc() {
			return desc;
		}
	};

	public Fragment(LdoD ldoD, String title, String xmlId) {
		setLdoD(ldoD);
		setTitle(title);
		setXmlId(xmlId);
	}

	@Atomic(mode = TxMode.WRITE)
	public void remove() {
		setLdoD(null);

		getTextPortion().remove();

		for (FragInter inter : getFragmentInterSet()) {
			inter.remove();
		}

		for (Source source : getSourcesSet()) {
			source.remove();
		}

		for (RefText ref : getRefTextSet()) {
			// the reference is removed
			ref.remove();
		}

		deleteDomainObject();
	}

	public List<FragInter> getSortedInterps() {
		List<FragInter> interps = new ArrayList<FragInter>(
				getFragmentInterSet());

		Collections.sort(interps);

		return interps;
	}

	public List<SourceInter> getSortedSourceInter() {
		List<SourceInter> interps = new ArrayList<SourceInter>();

		for (FragInter inter : getFragmentInterSet()) {
			if ((inter.getSourceType() == EditionType.AUTHORIAL)) {
				interps.add((SourceInter) inter);
			}
		}

		Collections.sort(interps);

		return interps;
	}

	public ExpertEditionInter getExpertEditionInter(String editor) {
		for (FragInter inter : getFragmentInterSet()) {
			if (inter.getSourceType() == EditionType.EDITORIAL) {
				ExpertEditionInter edInter = (ExpertEditionInter) inter;
				if (edInter.getExpertEdition().getEditor().equals(editor)) {
					return edInter;
				}
			}
		}
		return null;
	}

	public int getNumberOfInter4Edition(Edition edition) {
		int number = 0;
		for (FragInter inter : getFragmentInterSet()) {
			if (inter.belongs2Edition(edition)) {
				number = number + 1;
			}
		}
		return number;
	}

	public Surface getSurface(String xmlId) {
		for (Source source : getSourcesSet()) {
			if (source.getFacsimile() != null) {
				for (Surface surface : source.getFacsimile().getSurfaces()) {
					if (xmlId.equals(surface.getXmlId())) {
						return surface;
					}
				}
			}
		}
		return null;
	}

	public FragInter getFragInter(String xmlId) {
		for (FragInter inter : getFragmentInterSet()) {
			if (xmlId.equals(inter.getXmlId())) {
				return inter;
			}
		}
		return null;
	}
	
}

src/main/webapp/WEB-INF/jsp/fragment/body.jsp
<%@ include file="/WEB-INF/jsp/common/tags-head.jsp"%>
<div id="fragmentBody">
    <div class="container">
        <div class="row">
            <div class="col-md-9">
                <c:choose>
                    <c:when test="${inters.size() == 0}"><%@ include
                            file="/WEB-INF/jsp/fragment/interEmpty.jsp"%></c:when>
                    <c:when
                        test="${(inters.size() == 1) && (inters.get(0).sourceType=='EDITORIAL')}"><%@ include
                            file="/WEB-INF/jsp/fragment/interEditorial.jsp"%></c:when>
                    <c:when
                        test="${(inters.size() == 1) && (inters.get(0).sourceType=='AUTHORIAL')}"><%@ include
                            file="/WEB-INF/jsp/fragment/interAuthorial.jsp"%></c:when>
                    <c:when
                        test="${(inters.size() == 1) && (inters.get(0).sourceType=='VIRTUAL')}"><%@ include
                            file="/WEB-INF/jsp/fragment/interVirtual.jsp"%></c:when>
                    <c:when test="${(inters.size() > 1) && (inters.get(0).sourceType!='VIRTUAL')}"><%@ include
                            file="/WEB-INF/jsp/fragment/inter2Compare.jsp"%></c:when>
                    <c:otherwise><%@ include
                            file="/WEB-INF/jsp/fragment/virtual2Compare.jsp"%></c:otherwise>
                </c:choose>
            </div>
            <div class="col-md-3">
                <%@ include file="/WEB-INF/jsp/fragment/navegation.jsp"%>
            </div>
        </div>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/fragment/facsimile.jsp
<%@ include file="/WEB-INF/jsp/common/tags-head.jsp"%>
<script type="text/javascript">
$(document).ready(function() {
    $('[id="backward"][data-toggle="button"]').on('click', function() {
	var data = new Array();
	$('#baseinter :checked').each(function() {
	    data.push(this.value);
	});
	var selDiff = $('input:checkbox[name=diff]').is(':checked');
	var selDel = $('input:checkbox[name=del]').is(':checked');
	var selIns = $('input:checkbox[name=ins]').is(':checked');
	var selSubst = $('input:checkbox[name=subst]').is(':checked');
	var selNotes = $('input:checkbox[name=notes]').is(':checked');
	var selFacs = $('input:checkbox[name=facs]').is(':checked');
	var pbText = $('#backward').val();
	$.get("${contextPath}/fragments/fragment/inter/authorial", {
	    interp : data,
	    diff : selDiff,
	    del : selDel,
	    ins : selIns,
	    subst : selSubst,
	    notes : selNotes,
	    facs : selFacs,
	    pb : pbText
	}, function(html) {
	    $("#fragmentTranscription").replaceWith(html);
	});
    });
});
</script>
<script type="text/javascript">
$(document).ready(function() {
    $('[id="forward"][data-toggle="button"]').on('click', function() {
	var data = new Array();
	$('#baseinter :checked').each(function() {
	    data.push(this.value);
	});
	var selDiff = $('input:checkbox[name=diff]').is(':checked');
	var selDel = $('input:checkbox[name=del]').is(':checked');
	var selIns = $('input:checkbox[name=ins]').is(':checked');
	var selSubst = $('input:checkbox[name=subst]').is(':checked');
	var selNotes = $('input:checkbox[name=notes]').is(':checked');
	var selFacs = $('input:checkbox[name=facs]').is(':checked');
	var pbText = $('#forward').val();
	$.get("${contextPath}/fragments/fragment/inter/authorial", {
	    interp : data,
	    diff : selDiff,
	    del : selDel,
	    ins : selIns,
	    subst : selSubst,
	    notes : selNotes,
	    facs : selFacs,
	    pb : pbText
	}, function(html) {
	    $("#fragmentTranscription").replaceWith(html);
	});
    });
});
</script>
<div id="fragmentTranscription" class="row col-md-12">
    <div class="row">
        <h4>${inters.get(0).title}</h4>
        <div class="row">
            <div class="col-md-6">
                <c:choose>
                    <c:when test="${prevsurface != null}">
                        <button class="btn btn-sm pull-left"
                            type="button" id="backward"
                            value="${prevpb.externalId}"
                            data-toggle="button">
                            <span class="glyphicon glyphicon-backward"></span>
                        </button>
                    </c:when>
                    <c:otherwise>
                        <button class="btn btn-sm pull-left"
                            type="button" id="backward" disabled>
                            <span class="glyphicon glyphicon-backward"></span>
                        </button>
                    </c:otherwise>
                </c:choose>
                <c:choose>
                    <c:when test="${nextsurface != null}">
                        <button class="btn btn-sm pull-right"
                            type="button" id="forward"
                            value="${nextpb.externalId}"
                            data-toggle="button">
                            <span class="glyphicon glyphicon-forward"></span>
                        </button>
                    </c:when>
                    <c:otherwise>
                        <button class="btn btn-sm pull-right"
                            type="button" id="forward" disabled>
                            <span class="glyphicon glyphicon-forward"></span>
                        </button>
                    </c:otherwise>
                </c:choose>
            </div>
        </div>
        <div id="facsimileTranscription" class="row">
            <div class="col-md-6">
                <div class="item">
                    <img src="/facs/${surface.graphic}"
                        class="img-responsive" alt="Responsive image" />
                </div>
            </div>
            <c:choose>
                <c:when
                    test="${inters.get(0).lastUsed.sourceType=='EDITORIAL'}">
                    <div class="well col-md-6" id="content"
                        style="font-family: georgia;">
                        <p>${writer.getTranscription()}</p>
                    </div>
                </c:when>
                <c:otherwise>
                    <div class="well col-md-6" id="content"
                        style="font-family: courier;">
                        <p>${writer.getTranscription()}</p>
                    </div>
                </c:otherwise>
            </c:choose>
        </div>
        <div class="row">
            <div class="col-md-6">
                <c:choose>
                    <c:when test="${prevsurface != null}">
                        <button class="btn btn-sm pull-left"
                            type="button" id="backward"
                            value="${prevpb.externalId}"
                            data-toggle="button">
                            <span class="glyphicon glyphicon-backward"></span>
                        </button>
                    </c:when>
                    <c:otherwise>
                        <button class="btn btn-sm pull-left"
                            type="button" id="backward" disabled>
                            <span class="glyphicon glyphicon-backward"></span>
                        </button>
                    </c:otherwise>
                </c:choose>
                <c:choose>
                    <c:when test="${nextsurface != null}">
                        <button class="btn btn-sm pull-right"
                            type="button" id="forward"
                            value="${nextpb.externalId}"
                            data-toggle="button">
                            <span class="glyphicon glyphicon-forward"></span>
                        </button>
                    </c:when>
                    <c:otherwise>
                        <button class="btn btn-sm pull-right"
                            type="button" id="forward" disabled>
                            <span class="glyphicon glyphicon-forward"></span>
                        </button>
                    </c:otherwise>
                </c:choose>
            </div>
        </div>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/fragment/inter2CompareSideBySide.jsp
<%@ include file="/WEB-INF/jsp/common/tags-head.jsp"%>
<div id=fragmentComparison class="row">
    <div class="row">
        <c:forEach var="inter" items="${inters}">
            <div id="fragmentTranscription" class="col-md-6">
                <h4>${inter.title}</h4>
                <div class="well">
                    <c:choose>
                        <c:when test="${writer.showSpaces}">
                            <p style="font-family: monospace;">${ldod:getTranscription(writer,inter)}</p>
                        </c:when>
                        <c:otherwise>
                            <p style="font-family: georgia;">${ldod:getTranscription(writer,inter)}</p>
                        </c:otherwise>
                    </c:choose>
                </div>
            </div>
        </c:forEach>
    </div>
    <br>
    <div class="row">
        <c:forEach var="inter" items="${inters}">
            <div id="interMeta" class="col-md-6">
                <div class="well">
                    <p>${inter.metaTextual}</p>
                </div>
            </div>
        </c:forEach>
    </div>
</div>

src/main/webapp/WEB-INF/jsp/fragment/interEmpty.jsp
<%@ include file="/WEB-INF/jsp/common/tags-head.jsp"%>

<div id=fragmentInter class="row">
        <h4 class="text-center">${fragment.title}</h4>
</div>

src/main/webapp/WEB-INF/jsp/fragment/transcription.jsp
<%@ include file="/WEB-INF/jsp/common/tags-head.jsp"%>

<div id="fragmentTranscription" class="row">

    <div class="row">
        <h4 class="text-center">${inters.get(0).title}</h4>
        <c:choose>
            <c:when
                test="${inters.get(0).lastUsed.sourceType=='EDITORIAL'}">
                <div class="well" id="content"
                    style="font-family: georgia; font-size: medium;">
                    <p>${writer.getTranscription()}</p>
                </div>
            </c:when>
            <c:otherwise>
                <div class="well" id="content"
                    style="font-family: courier;">
                    <p>${writer.getTranscription()}</p>
                </div>
            </c:otherwise>
        </c:choose>
    </div>
</div>