src/main/java/pt/ist/socialsoftware/edition/domain/Source.java
package pt.ist.socialsoftware.edition.domain;

public abstract class Source extends Source_Base implements Comparable<Source> {

	public enum SourceType {
		MANUSCRIPT("manuscript"), PRINTED("printed");

		private final String desc;

		SourceType(String desc) {
			this.desc = desc;
		}

		public String getDesc() {
			return desc;
		}
	};

	public abstract String getName();

	public abstract String getMetaTextual();

	public void remove() {
		setFragment(null);

		// A source may not have a facsimile ???? - need to be checked with
		// encoders
		if (getFacsimile() != null) {
			getFacsimile().remove();
		}

		for (SourceInter inter : getSourceIntersSet()) {
			removeSourceInters(inter);
		}

		deleteDomainObject();
	}

	@Override
	public int compareTo(Source other) {
		return getName().compareTo(other.getName());
	}
}

src/main/java/pt/ist/socialsoftware/edition/controller/SourceController.java
package pt.ist.socialsoftware.edition.controller;

import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import pt.ist.socialsoftware.edition.domain.Fragment;
import pt.ist.socialsoftware.edition.domain.LdoD;
import pt.ist.socialsoftware.edition.domain.Source;

@Controller
@RequestMapping("/source")
public class SourceController {

	@RequestMapping(method = RequestMethod.GET, value = "/list")
	public String getListOfSources(Model model) {

		LdoD ldoD = LdoD.getInstance();

		List<Source> sources = new ArrayList<Source>();
		for (Fragment frag : ldoD.getFragmentsSet()) {
			sources.addAll(frag.getSourcesSet());
		}

		Collections.sort(sources);

		model.addAttribute("sources", sources);

		return "source/listSources";
	}
}

src/main/webapp/WEB-INF/jsp/source/listSources.jsp
<%@ include file="/WEB-INF/jsp/common/tags-head.jsp"%>
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
<head>
<%@ include file="/WEB-INF/jsp/common/meta-head.jsp"%>
</head>
<body>
    <%@ include file="/WEB-INF/jsp/common/fixed-top-ldod-header.jsp"%>

    <div class="container">
        <h3 class="text-center">
            <spring:message code="authorial.source" />
            (${sources.size()})
        </h3>
        <table class="table table-bordered table-condensed">
            <thead>
                <tr>
                    <th><spring:message code="header.documents" /></th>
                    <th><spring:message
                            code="general.transcription" /></th>
                    <th><spring:message code="general.date" /></th>
                    <th><spring:message code="general.type" /></th>
                    <th><spring:message code="general.LdoDLabel" /></th>
                    <th><spring:message code="general.format" /></th>
                    <th><spring:message code="general.material" /></th>
                    <th><spring:message code="general.columns" /></th>
                    <th><spring:message code="general.facsimiles" /></th>
                </tr>
            <tbody>
                <c:forEach var="source" items='${sources}'>
                    <tr>
                        <td>${source.name}</td>
                        <td><c:forEach var='iter'
                                items='${source.getSourceIntersSet()}'>
                                <a
                                    href="${contextPath}/fragments/fragment/inter/${iter.externalId}">
                                    ${iter.title}</a>
                            </c:forEach></td>
                        <td>${source.getDate().toString("dd-MM-yyyy")}</td>
                        <td><c:choose>
                                <c:when
                                    test='${source.getType()=="MANUSCRIPT"}'>
                                    <c:forEach var='handNote'
                                        items='${source.getHandNoteSet()}'>
                                        <spring:message
                                            code="general.manuscript" />(${handNote.getMedium()})
                                        <br>
                                    </c:forEach>
                                    <c:forEach var='typeNote'
                                        items='${source.getTypeNoteSet()}'>
                                        <spring:message
                                            code="general.typescript" />(${typeNote.getMedium()})
                                        <br>
                                    </c:forEach>
                                </c:when>
                                <c:otherwise>
                                    <spring:message
                                        code="general.printed" />
                                </c:otherwise>
                            </c:choose></td>
                        <td><c:if
                                test='${source.getType()=="MANUSCRIPT"}'>
                                <c:choose>
                                    <c:when
                                        test='${source.getHasLdoDLabel()}'>
                                        <spring:message
                                            code="general.yes" />
                                    </c:when>
                                    <c:otherwise>
                                        <spring:message
                                            code="general.no" />
                                    </c:otherwise>
                                </c:choose>
                            </c:if></td>
                        <td><c:if
                                test='${source.getType()=="MANUSCRIPT"}'>
                                <c:choose>
                                    <c:when
                                        test='${source.getForm()=="LEAF"}'><spring:message
                                            code="general.leaf" /></c:when>
                                    <c:otherwise></c:otherwise>
                                </c:choose>
                            </c:if></td>
                        <td><c:if
                                test='${source.getType()=="MANUSCRIPT"}'>
                                <c:choose>
                                    <c:when
                                        test='${source.getMaterial()=="PAPER"}'><spring:message
                                            code="general.paper" /></c:when>
                                    <c:otherwise></c:otherwise>
                                </c:choose>
                            </c:if></td>
                        <td><c:if
                                test='${source.getType()=="MANUSCRIPT"}'>${source.getColumns()}</c:if></td>
                        <td><c:forEach var='surface'
                                items='${source.getFacsimile().getSurfaces()}'
                                varStatus="counter">
                                <a href="/facs/${surface.getGraphic()}">(${counter.index+1})
                                    ${source.name} </a>
                                <br>
                            </c:forEach></td>
                    </tr>
                </c:forEach>
            </tbody>
        </table>
    </div>
</body>
</html>